"""Add last_seen_at to RawDocument

Revision ID: 9d14d2974166
Revises: 005
Create Date: 2026-05-15 16:46:34.934003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d14d2974166'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_chunks_embedding_hnsw'), table_name='processed_chunks', postgresql_ops={'(embedding::halfvec(3072))': 'halfvec_cosine_ops'}, postgresql_with={'ef_construction': '128', 'm': '16'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_processed_chunks_embedding_id'), table_name='processed_chunks')
    op.create_index('ix_processed_chunks_embedding', 'processed_chunks', ['embedding_id'], unique=False)
    op.drop_constraint(op.f('processed_chunks_document_id_fkey'), 'processed_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'processed_chunks', 'raw_documents', ['document_id'], ['id'])
    op.add_column('raw_documents', sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_documents', 'last_seen_at')
    op.drop_constraint(None, 'processed_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('processed_chunks_document_id_fkey'), 'processed_chunks', 'raw_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_processed_chunks_embedding', table_name='processed_chunks')
    op.create_index(op.f('ix_processed_chunks_embedding_id'), 'processed_chunks', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_processed_chunks_embedding_hnsw'), 'processed_chunks', [sa.literal_column('(embedding::halfvec(3072))')], unique=False, postgresql_ops={'(embedding::halfvec(3072))': 'halfvec_cosine_ops'}, postgresql_with={'ef_construction': '128', 'm': '16'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
