apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    # url: KB-Pipeline-Postgres:5432
    url: sg-property-kb-postgres:5432
    database: kb_pipeline_db
    user: kb_user
    secureJsonData:
      password: kb_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true